version: '3.8'

services:
  app:
    build: .
    ports:
      - "PORT_PLACEHOLDER:PORT_PLACEHOLDER"
    environment:
      - NODE_ENV=production
      - PORT=PORT_PLACEHOLDER
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:PORT_PLACEHOLDER"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "NGINX_PORT_PLACEHOLDER:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3 